export const COLORS = {
    primary: '#F47031',
    white: '#FFFFFF',
    black: '#000',
    transparent_primaty: 'rgba(255, 255, 255, 0.45)',
    slider_unfill: '#FEF1EA',
    shadow_color: '#F3DACE',
    drop_shadow: '#CF5D26',
    questionColor: '#37271F',
    borderShadow: '#ED946A',
    contentColor: '#838181',
    backgroundColor: '#FCDBCB',
    contentThree: '#E7E7E7',
    screenBackground: '#FCDBCB',
    contentTwo: '#838181',
    color_9DA499: '#9DA499',
    blue: '#A04FE3',
    blueShedow: "#7C31BA",
    color_53ADF0: '#53ADF0',
    color_398DCC: "#398DCC",
    color_F3F3F3: '#F3F3F3',
    color_EEEDED: '#EEEDED',
    color_FAFAFA: '#FAFAFA',
    devider: '#FFE6D9',
    color_F6F6F6: '#F6F6F6',
    green: '#77C93C',
    communityTextColor: '#1A1D28',
    communitytagColor: '#797B82',
    communitysnellColor: '#F7CA45',
    communitylevelColor: '#77C93C',
    communityHrColor: '#5C6064',
    dialog_transparent: 'rgba(59, 66, 74, 0.33)',
    dialog_line_coloe: '#D9D9D9',
    dialog_item_background: '#F6F6F6',
    desColor:'#FDD5C2'

}

export const IMAGES = {
    logo: require('./images/logo.png'),
    rush: require('./images/rush.png'),
    solana: require('./images/solana.png'),
    back: require('./images/ic_back.png'),
    success: require('./images/success.png'),
    learning_logo: require('./images/learning_logo.png'),
    cancel: require('./images/cancel.png'),
    mask: require('./images/mask_icon.png'),
    learning: require('./images/learning.png'),
    strip: require('./images/strip.png'),
    background: require('./images/background_one.png'),
    backgroundWhite: require('./images/background_two.png'),
    roundOne: require('./images/round_one.png'),
    roundTwo: require('./images/round_two.png'),
    roundThree: require('./images/round_three.png'),
    right: require('./images/right.png'),
    bgCreateProfile: require('./images/bgCreateProfile.png'),
    phantom: require('./images/phantom.png'),
    solflare: require('./images/solflare.png'),
    grow: require('./images/grow.png'),
    email: require('./images/email.png'),
    congrates: require('./images/congrates.png'),
    home: require('./images/home_unfill.png'),
    homeFill: require('./images/home_fill.png'),
    courses: require('./images/course_unfill.png'),
    coursesFill: require('./images/courses_fill.png'),
    leaderboard: require('./images/leaderboard_unfill.png'),
    leaderboardFill: require('./images/leaderboard_fill.png'),
    comment: require('./images/comment_unfill.png'),
    commentFill: require('./images/comment_fill.png'),
    profile: require('./images/profile_unfill.png'),
    profileFill: require('./images/profile_fill.png'),
    backgroundHome: require('./images/home_bg.png'),
    noti: require('./images/noti.png'),
    dropdown: require('./images/dropdown.png'),
    languageIcon: require('./images/language_icon.png'),
    lock: require('./images/lock.png'),
    lactureImage: require('./images/lacture_image.png'),
    lactureLock: require('./images/lession_lock.png'),
    frame: require('./images/frame_new.png'),
    search: require('./images/search.png'),
    shortby: require('./images/shortby.png'),
    communityimage: require('./images/communityimage.png'),
    share: require('./images/share.png'),
    favourite: require('./images/favourite.png'),
    message: require('./images/message.png'),
    favouritefill: require('./images/favouritefill.png'),
    messagefill: require('./images/messagefill.png'),
    user1: require('./images/user1.png'),
    user2: require('./images/user2.png'),
    threedots: require('./images/threedots.png'),
    editpost: require('./images/editpost.png'),
    close: require('./images/close.png'),
    recent: require('./images/recent.png'),
    popular: require('./images/popular.png'),
    bookmark: require('./images/bookmark.png'),
    nointerested: require('./images/nointerested.png'),
    report: require('./images/report.png'),
    blockimahe: require('./images/blockimahe.png'),
    backgroundWelcome: require('./images/welcome_bg.png'),
    successBackground: require('./images/success_bg.png')

}